apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-web-python
spec:
  rules:
  - host: <hostname>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: example-web-python
          servicePort: 5000
